[package]
name = "hex"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]

[dependencies]
websocket = "0.20"
futures = "0.1.14"
tokio-core = "0.1"
serde_json = "1.0"
serde = "1.0"

[dependencies.hex_music]
path = "../music/"
