[package]
name = "hex"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]

[dependencies]
websocket = "0.20"
futures = "0.1.14"
tokio-core = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
failure = "0.1"
failure_derive = "0.1"
toml = "0.4"

[dependencies.chromaprint]
git = "https://github.com/bytesnake/rust-chromaprint"

[dependencies.hex_music]
path = "./music/"
